### ISSUE TITLE
The `tests` folder is being packaged in PyPI

### ISSUE THREAD

**Issue by sugatoray** [michael-gracie/gslides#47]
* gslides version: 0.1.0
* Python version: 3.7
* Operating System: Ubuntu 20.04

### Description

The current version includes `tests` in the PyPI package. Ideally, `tests` should be recursively excluded. But I see that it has been recursively included. Is there any particular reason why `tests` folder was added to the PyPI package?

### Suggested Fix

Please change the following in `MANIFEST.in` and push a new version `v0.7.1` to PyPI.

```diff
  include AUTHORS.rst
  include LICENSE
  include README.rst
  include CHANGELOG.rst
  include *.txt
  include gslides/config/*.yaml
  include .isort.cfg

- recursive-include tests *
+ recursive-exclude tests *
  recursive-exclude * __pycache__
  recursive-exclude * *.py[co]
  recursive-exclude img *.png

recursive-include docs *.rst conf.py Makefile make.bat *.jpg *.png *.gif
```

### What I Did

I am working on adding `gslides` to conda-forge. That's when this was discovered. Once the :bulb: [**PR**](https://github.com/conda-forge/staged-recipes/pull/17223) is ready, I will share updates.

**Comment by sugatoray** [comment]
cc: @michael-gracie

**Comment by michael-gracie** [comment]
Sorry for the slow response, and happy you are adding to `conda-forge`. I can cut a release this weekend

**Comment by michael-gracie** [comment]
@sugatoray I've cut a new release with the change!

**Comment by sugatoray** [comment]
Great! By the way, `gslides` is available on conda-forge (I am not sure if I told you about it or not). So, do you want to make the update to gslides on conda-forge?

If you do, please fork the repo: https://github.com/conda-forge/gslides-feedstock and just change (same as that on PyPI for the `tar.gz` source file) the `version` and `sha256` and then submit the PR.
